#!/bin/bash

EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: ./answer <article_text> <questions_text>"
  exit $E_BADARGS
fi

export NLTK_DATA=/afs/andrew.cmu.edu/usr/ysim/nltk_data

cd answer_files
./answer.py ../$1 ../$2
