#!/bin/bash

EXPECTED_ARGS=2
E_BADARGS=65

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: ./ask <article_text> <N>"
  exit $E_BADARGS
fi

export NLTK_DATA=/afs/andrew.cmu.edu/usr/ysim/nltk_data

cd ask_files
./ask.py --txt ../$1 --N $2
